### ISSUE TITLE
jwt秘钥怎么设置

### ISSUE THREAD

**Issue by gaoyuhengcn** [xencio/xencio-box#2]
[Nest] 1023063  - 2022/12/04 11:20:24   ERROR [ExceptionHandler] JwtStrategy requires a secret or key
TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (/root/box/xencio-box/node_modules/passport-jwt/lib/strategy.js:45:15)
    at new MixinStrategy (/root/box/xencio-box/node_modules/@nestjs/passport/dist/passport/passport.strategy.js:32:13)
    at new JwtStrategy (/root/box/xencio-box/src/routes/auth/auth.strategy.ts:11:5)
    at Injector.instantiateClass (/root/box/xencio-box/node_modules/@nestjs/core/injector/injector.js:330:19)
    at callback (/root/box/xencio-box/node_modules/@nestjs/core/injector/injector.js:48:41)
    at Injector.resolveConstructorParams (/root/box/xencio-box/node_modules/@nestjs/core/injector/injector.js:122:24)
    at Injector.loadInstance (/root/box/xencio-box/node_modules/@nestjs/core/injector/injector.js:52:9)
    at Injector.loadProvider (/root/box/xencio-box/node_modules/@nestjs/core/injector/injector.js:74:9)
    at async Promise.all (index 5)
    at InstanceLoader.createInstancesOfProviders (/root/box/xencio-box/node_modules/@nestjs/core/injector/instance-loader.js:44:9)

说好像是缺失JWT秘钥，可这个应该怎么设置

**Comment by gaoyuhengcn** [comment]
自问自答 mv .env.example .env
